name: finance_app
description: "Finance monitoring app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  sqflite: any
  path_provider: any
  path: any
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true